# Generated by Django 5.2.3 on 2025-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('3D', '3D Model'), ('DRAWING', 'Technical Drawing'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
