# Generated by Django 5.2.3 on 2025-07-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_project_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='project',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dimensions',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pcs', help_text='e.g., pcs, kg, m', max_length=20),
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_types', to='core.materialtype')),
            ],
            options={
                'verbose_name': 'Stock Type',
                'verbose_name_plural': 'Stock Types',
                'unique_together': {('material_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stocktype'),
        ),
    ]
