# Generated by Django 5.2.3 on 2025-07-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_materialtype_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='core.project'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='dimensions',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.stocktype'),
        ),
    ]
