# Generated by Django 5.2.3 on 2025-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_inventoryitem_options_inventoryitem_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='project',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='dimensions',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, default='SN-DEFAULT', max_length=100, null=True),
        ),
    ]
