# Generated by Django 5.2.3 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_description_task_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
