# Generated by Django 5.2.3 on 2025-07-15 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projectcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this cutting list (e.g., Project ABC - Pipes)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuttingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_length', models.DecimalField(decimal_places=2, help_text='Cut length (mm)', max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_length_used', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated: cut_length * quantity', max_digits=10)),
                ('waste', models.DecimalField(decimal_places=2, default=0, help_text='Remaining offcut after cuts', max_digits=10)),
                ('cutting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.cuttinglist')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem')),
            ],
        ),
    ]
