# Generated by Django 5.2.3 on 2025-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cuttinglist_cuttinglistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='m', help_text='e.g., m for meters', max_length=20),
        ),
    ]
