# Generated by Django 5.2.3 on 2025-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_inventoryitem_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length per piece (in meters)', max_digits=10),
        ),
    ]
