# Generated by Django 5.2.3 on 2025-07-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quote_quoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='OUT', max_length=3)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('customer_or_supplier', models.CharField(help_text='Customer for outgoing or Supplier for incoming', max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='shipping_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shipment')),
            ],
        ),
    ]
