# Generated by Django 5.2.3 on 2025-07-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shipment_shipmentitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='expected_arrival',
            new_name='expected_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='customer_or_supplier',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ship_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='Unnamed Shipment', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='Incoming', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
