# Generated by Django 5.2.3 on 2025-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('production', 'Production'), ('qc', 'Quality Control'), ('sales', 'Sales'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('Director', 'Director'), ('CNC Operator', 'CNC Operator'), ('Production Manager', 'Production Manager'), ('CAD Designer', 'CAD Designer'), ('Owner', 'Owner'), ('Manual Labour', 'Manual Labour')], max_length=32),
        ),
    ]
