"""
Django settings for erp_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_937d=2y1remzab10ow*vhnri6(y#k&o!(cr-(&g+#^7a4b!dz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'channels',
    
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.permission_gate.PermissionGateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'core.middleware.LoginRequiredMiddleware',  # 👈 ADD THIS
]

# settings.py
PERMISSION_VIEW_MAP = {
    # Projects
    "project_list":   ["core.view_project"],
    "project_detail": ["core.view_project"],
    "project_create": ["core.add_project"],
    "project_delete": ["core.delete_project"],
    "upload_project_file": ["core.add_projectfile"],
    "add_production_cost": ["core.add_productioncost"],

    # Customers
    "customer_list":   ["core.view_customer"],
    "customer_detail": ["core.view_customer"],
    "customer_create": ["core.add_customer"],
    "add_customer":    ["core.add_customer"],

    # Inventory
    "inventory_list":   ["core.view_inventoryitem"],
    "inventory_create": ["core.add_inventoryitem"],
    "inventory_add_stock": ["core.add_inventoryitem"],

    # Tasks
    "task_dashboard": ["core.view_task"],
    "my_tasks":       ["core.view_task"],
    "task_create":    ["core.add_task"],
    # task_detail: GET can view, POST changing status requires change permission
    "task_detail": {"*": ["core.view_task"], "POST": ["core.change_task"]},

    # Cutting lists
    "cutting_list_dashboard": ["core.view_cuttinglist"],
    "cutting_list_create":    ["core.add_cuttinglist"],
    "cutting_list_detail":    ["core.view_cuttinglist"],
    "cutting_list_pdf_export": ["core.view_cuttinglist"],

    # Quotes
    "quote_dashboard":   ["core.view_quote"],
    "quote_create":      ["core.add_quote"],
    "quote_detail":      ["core.view_quote"],
    "quote_pdf_export":  ["core.view_quote"],

    # Calendar & Reminders
    "calendar_events":   ["core.view_task", "core.view_project"],
    "add_reminder":      ["core.add_reminder"],
    "edit_reminder":     ["core.change_reminder"],
    "delete_reminder":   ["core.delete_reminder"],

    # Shipping
    "shipping_dashboard": ["core.view_shipment"],
    "shipment_detail":    ["core.view_shipment"],
    "shipment_create":    ["core.add_shipment"],

    # Chat / Conversations (adjust as you like)
    "conversation_list":   ["core.view_conversation"],
    "conversation_detail": ["core.view_conversation"],
    "chat_dashboard":      ["core.view_chat"],
    "chat_create":         ["core.add_chat"],
    "chat_detail":         ["core.view_chat"],

    # Invoices
    "invoice_dashboard": ["core.view_invoice"],
    "invoice_create":    ["core.add_invoice"],
    "invoice_detail":    ["core.view_invoice"],

    # Stats
    "stats_dashboard": ["core.view_invoice"],  # conservative gate
    # Users/roles
    "user_list":   ["auth.view_user"],
    "assign_role": ["core.change_userrole"],
}

ROOT_URLCONF = 'erp_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp_project.wsgi.application'
ASGI_APPLICATION = 'erp_project.asgi.application'

# Redis for WebSockets
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Redis server
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Sarajevo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redirect unauthenticated users
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Optional: redirect after logout
LOGOUT_REDIRECT_URL = '/login/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



